@startuml 訪問者システム
skinparam componentStyle rectangle

[Webページ] o-- [ユーザID]

[ユーザID] o-- [パスワード]
[ユーザID] o-- [名前]
[ユーザID] o-- [学校名]
[ユーザID] o-- [所属名]
[ユーザID] o-- [メールアドレス]
[ユーザID] o-- [電話番号]
[ユーザID] o-- [年齢]
[ユーザID] o-- [登録・参照]
[ユーザID] o-- [他の訪問者の情報を参照]
[ユーザID] o-- [登録情報を変更・削除する]



@enduml