@startuml 通販クラス図
skinparam classAttributeIconSize 0

class 顧客 {
  名前
  住所
  電話番号
  メールアドレス
}

class アカウント {
  ユーザーID
  パスワード
}

class 商品 {
  ID
  商品情報
  在庫数
  カート
}

class 注文 {
  注文番号
  注文日
  数量
  合計金額
}

class 支払い {
  クレジットカード情報
}

class 工場 {
  出荷依頼
}

class 配送 {
  配送先住所
  配送業者
}

class 返品返金 {
  理由
  日付
  金額
}

顧客 -- アカウント : 保有
顧客 -- 注文 : 注文する
注文 -- 商品 : 含む
注文 -- 支払い : 支払う
注文 -- 配送 : 配送する
注文 -- 返品返金 : 返品・返金
注文 -- 工場 : 出荷依頼

@enduml