@startuml 通販クラス図
skinparam classAttributeIconSize 0

class 顧客 {
  - 名前
  - 住所
  - 電話番号
  - メールアドレス
  + アカウント()
  + 注文()
}

class アカウント {
  - 利用者ID
  - パスワード
}

class 商品 {
  - ID
  - 商品情報
  - 在庫数
  - カート
}

class 注文 {
  - 注文番号
  - 注文日
  - 数量
  - 合計金額
  + 商品()
  + 支払い()
  + 配送()
  + 返品返金()
  + 工場()
}

class 支払い {
  - クレジットカード情報
}

class 工場 {
  - 生産指示
  - 出荷依頼
}

class 配送 {
  - 配送先住所
  - 配送業者
}

class 返品返金 {
  - 理由
  - 日付
  - 金額
}

顧客 <-- アカウント
顧客 <-- 注文
注文 <-- 商品
注文 <-- 支払い
注文 <-- 配送
注文 <-- 返品返金
注文 <-- 工場

@enduml