@startuml 会議室予約システム
skinparam componentStyle rectangle

[ブラウザ] o-- [ログイン]
[ブラウザ] o-- [ログアウト]

[ユーザー] o-- [ユーザーID]
[ユーザー] o-- [ユーザー名]

[会議室] o-- [会議室名]

[予約] o-- [予約番号]
[予約] o-- [会議開始終了時刻]
[予約] o-- [利用時刻]
[予約] o-- [日付]
[予約] o-- [会議の目的]
[予約] o-- [利用目的]

[ユーザー] o-- [予約]
[会議室] o-- [予約]

[ログイン] o-- [ユーザーID]
[ログアウト] o-- [ユーザーID]

@enduml